### ISSUE TITLE
New Mod Request: Hand skins. skins_hand

### ISSUE THREAD

**Issue by bell07** [bell07/minetest-player_api_modpack#3]
Something like https://github.com/jordan4ibanez/newhand. Skinify the player hand

**Comment by BruceMustache** [comment]
- [ ] To work on latest minetest first needs to accept this PR https://github.com/jordan4ibanez/newhand/pull/11
- [ ] Fix a security issue as say here https://github.com/minetest/minetest/issues/8559
- [ ] newhand compatible with any skin mod

**Comment by bell07** [comment]
Done in https://github.com/bell07/minetest-player_api_modpack/commit/3803ca286c5e084f7101961b3d9a1a906a23d57f :-)
